java_test(
    name = "hello",
    srcs = [
        "RunCucumberTest.java",
        "Stepdefs.java",
    ],
    args = ["test_output=all"],
    test_class = "hellocucumber.RunCucumberTest",
    deps = ["//:tests"],
)
