java_binary(
    name = "VertxLauncher",
    srcs = [
            "MyVerticle.java",
            "VertxLauncher.java",
        ],
    main_class = "src/main/java/hellocucumber/VertxLauncher",
    deps = ["//:sources"],
)